name: Release

on:
  release:
    types: [published]

permissions: {}

jobs:
  build-and-test:
    permissions:
      contents: read
    uses: ./.github/workflows/build-and-test.yaml

  goreleaser:
    needs: [build-and-test]
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch tags
        run: git fetch --force --tags

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.25.x

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: "~> v1"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GORELEASER_GITHUB_TOKEN }}

      - name: Strip "v" prefix from tag
        run: echo "TAG_NAME=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV
        env:
          GITHUB_REF_NAME: ${{ github.ref_name }} 

      - name: Upload AMD64 DEB artifacts
        uses: actions/upload-artifact@v4
        with:
          name: alpacon_${{ env.TAG_NAME }}_linux_amd64.deb
          path: dist/alpacon_${{ env.TAG_NAME }}_linux_amd64.deb

      - name: Upload AMD64 RPM artifacts
        uses: actions/upload-artifact@v4
        with:
          name: alpacon_${{ env.TAG_NAME }}_linux_amd64.rpm
          path: dist/alpacon_${{ env.TAG_NAME }}_linux_amd64.rpm

      - name: Upload ARM64 DEB artifacts
        uses: actions/upload-artifact@v4
        with:
          name: alpacon_${{ env.TAG_NAME }}_linux_arm64.deb
          path: dist/alpacon_${{ env.TAG_NAME }}_linux_arm64.deb

      - name: Upload ARM64 RPM artifacts
        uses: actions/upload-artifact@v4
        with:
          name: alpacon_${{ env.TAG_NAME }}_linux_arm64.rpm
          path: dist/alpacon_${{ env.TAG_NAME }}_linux_arm64.rpm

  packagecloud-deploy:
    needs: [goreleaser]
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Strip "v" prefix from tag
        run: echo "TAG_NAME=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV
        env:
          GITHUB_REF_NAME: ${{ github.ref_name }} 

      - name: Download AMD64 DEB Artifacts
        uses: actions/download-artifact@v4
        with:
          name: alpacon_${{ env.TAG_NAME }}_linux_amd64.deb

      - name: Download AMD64 RPM Artifacts
        uses: actions/download-artifact@v4
        with:
          name: alpacon_${{ env.TAG_NAME }}_linux_amd64.rpm

      - name: Download ARM64 DEB Artifacts
        uses: actions/download-artifact@v4
        with:
          name: alpacon_${{ env.TAG_NAME }}_linux_arm64.deb

      - name: Download ARM64 RPM Artifacts
        uses: actions/download-artifact@v4
        with:
          name: alpacon_${{ env.TAG_NAME }}_linux_arm64.rpm

      - name: Upload AMD64 DEB to PackageCloud
        uses: danielmundi/upload-packagecloud@v1
        with:
          PACKAGE-NAME: alpacon_${{ env.TAG_NAME }}_linux_amd64.deb
          PACKAGECLOUD-USERNAME: alpacax
          PACKAGECLOUD-REPO: alpacon
          PACKAGECLOUD-DISTRIB: any/any
          PACKAGECLOUD-TOKEN: ${{ secrets.PACKAGECLOUD_TOKEN }}

      - name: Upload AMD64 RPM to PackageCloud
        uses: danielmundi/upload-packagecloud@v1
        with:
          PACKAGE-NAME: alpacon_${{ env.TAG_NAME }}_linux_amd64.rpm
          PACKAGECLOUD-USERNAME: alpacax
          PACKAGECLOUD-REPO: alpacon
          PACKAGECLOUD-DISTRIB: rpm_any/rpm_any
          PACKAGECLOUD-TOKEN: ${{ secrets.PACKAGECLOUD_TOKEN }}

      - name: Upload ARM64 DEB to PackageCloud
        uses: danielmundi/upload-packagecloud@v1
        with:
          PACKAGE-NAME: alpacon_${{ env.TAG_NAME }}_linux_arm64.deb
          PACKAGECLOUD-USERNAME: alpacax
          PACKAGECLOUD-REPO: alpacon
          PACKAGECLOUD-DISTRIB: any/any
          PACKAGECLOUD-TOKEN: ${{ secrets.PACKAGECLOUD_TOKEN }}

      - name: Upload ARM64 RPM to PackageCloud
        uses: danielmundi/upload-packagecloud@v1
        with:
          PACKAGE-NAME: alpacon_${{ env.TAG_NAME }}_linux_arm64.rpm
          PACKAGECLOUD-USERNAME: alpacax
          PACKAGECLOUD-REPO: alpacon
          PACKAGECLOUD-DISTRIB: rpm_any/rpm_any
          PACKAGECLOUD-TOKEN: ${{ secrets.PACKAGECLOUD_TOKEN }}
